name: Build and Release Github Actions Image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.variables.outputs.environment }}
      deploy-target: ${{ steps.variables.outputs.deploy-target }}
      external-contribution: ${{ steps.variables.outputs.external-contribution }}
      docker-registry: ${{ steps.variables.outputs.docker-registry }}
      docker-output: ${{ steps.variables.outputs.docker-output }}
      docker-output-file: ${{ steps.variables.outputs.docker-output-file }}
      docker-tag-suffix: ${{ steps.variables.outputs.docker-tag-suffix }}
    steps:
      - name: Setup slog values of GitHub env variables
        uses: rlespinasse/github-slug-action@e6f261660910b273384c5c42b17a0217881b217a # v5.6.0

      - name: Setup variables
        id: variables
        run: |
          set -eux -o pipefail

          # Which environment to use
          if ${{ github.event_name != 'pull_request' && (env.GITHUB_REF_NAME_SLUG == 'main' || env.GITHUB_REF_NAME_SLUG == 'staging') }}; then
            environment="${{ env.GITHUB_REF_NAME_SLUG }}"
          else
            environment=
          fi
          echo "environment=${environment}" >> $GITHUB_OUTPUT

          # Whether the deployment should be done to Scaleway or GitHub Container Registry
          if ${{ github.repository_owner == 'riseproject-dev' }} && [[ "${environment}" != '' ]]; then
            deploy_target="scw"
          else
            deploy_target="ghcr"
          fi
          echo "deploy-target=${deploy_target}" >> $GITHUB_OUTPUT

          # Which Docker registry to use
          if [[ "${deploy_target}" == "scw" ]]; then
            docker_registry="rg.fr-par.scw.cloud/funcscwriseriscvrunnerappqdvknz9s"
          elif ${{ github.event_name != 'pull_request' }}; then
            docker_registry="ghcr.io/${{ github.repository }}"
          else
            docker_registry="" # we do not push on PR
          fi
          echo "docker-registry=${docker_registry}" >> $GITHUB_OUTPUT

          # What's the Docker build output
          if [[ -z "${docker_registry}" ]]; then
            docker_output_file="/tmp/image.tar"
            docker_output="type=tar,dest=${docker_output_file}"
          else
            # we do not generate artifact if we push to registry
            docker_output_file=""
            docker_output=""
          fi
          echo "docker-output=${docker_output}" >> $GITHUB_OUTPUT
          echo "docker-output-file=${docker_output_file}" >> $GITHUB_OUTPUT

          # Which Docker tag suffix to use
          if ${{ github.event_name != 'pull_request' && env.GITHUB_REF_NAME_SLUG == 'main' }}; then
            docker_tag_suffix="latest"
          else
            docker_tag_suffix="${{ env.GITHUB_REF_NAME_SLUG }}"
          fi
          echo "docker-tag-suffix=${docker_tag_suffix}" >> $GITHUB_OUTPUT

  build-runner:
    strategy:
      matrix:
        include:
        - os: ubuntu
          os-version: 24.04
          runs-on: ubuntu-24.04-riscv
        # - os: ubuntu
        #   os-version: 26.04
        #   runs-on: ubuntu-latest # ubuntu-26.04-riscv-rva23 # Ubuntu 26.04 requires RVA23 hardware to run
    runs-on: ${{ matrix.runs-on }}
    needs: [setup]
    permissions:
      packages: write
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup slog values of GitHub env variables
        uses: rlespinasse/github-slug-action@e6f261660910b273384c5c42b17a0217881b217a # v5.6.0

      - name: Setup QEMU
        if: matrix.runs-on == 'ubuntu-latest'
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2

      - name: Login to Container Registry
        if: ${{ needs.setup.outputs.docker-registry != '' }}
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ needs.setup.outputs.docker-registry }}
          username: ${{ needs.setup.outputs.deploy-target == 'scw' && 'nologin' || github.actor }}
          password: ${{ needs.setup.outputs.deploy-target == 'scw' && secrets.SCW_SECRET_KEY || secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.os }}-${{ matrix.os-version }}-${{ needs.setup.outputs.docker-tag-suffix }} runner image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        env:
          SOURCE_DATE_EPOCH: 0 # No timestamps in layers
        with:
          context: runner
          file: runner/Dockerfile.${{ matrix.os }}
          platforms: linux/riscv64
          build-args: |
            OS_VERSION=${{ matrix.os-version }}
          tags: |
            ${{ needs.setup.outputs.docker-registry != '' && format('{0}/riscv-runner:{1}-{2}-{3}', needs.setup.outputs.docker-registry, matrix.os, matrix.os-version, needs.setup.outputs.docker-tag-suffix) || '' }}
          cache-from: |
            ${{ needs.setup.outputs.environment != '' && format('type=gha,scope=runner-{0}-{1}-{2}', matrix.os, matrix.os-version, needs.setup.outputs.environment) || '' }}
            ${{ needs.setup.outputs.environment == '' && format('type=gha,scope=runner-{0}-{1}-staging', matrix.os, matrix.os-version) || '' }}
          cache-to: |
            ${{ needs.setup.outputs.environment != '' && format('type=gha,scope=runner-{0}-{1}-{2},mode=max', matrix.os, matrix.os-version, needs.setup.outputs.environment) || '' }}
          push: ${{ needs.setup.outputs.docker-registry != '' }}
          pull: ${{ needs.setup.outputs.environment != '' }}
          outputs: ${{ needs.setup.outputs.docker-output }}

      - name: Upload ${{ matrix.os }}-${{ matrix.os-version }} runner image
        if: ${{ needs.setup.outputs.docker-output != '' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.os }}-${{ matrix.os-version }}-runner-image
          path: |
            ${{ needs.setup.outputs.docker-output-file }}

  build-dind:
    runs-on: ubuntu-24.04-riscv
    needs: [setup]
    permissions:
      packages: write
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup slog values of GitHub env variables
        uses: rlespinasse/github-slug-action@e6f261660910b273384c5c42b17a0217881b217a # v5.6.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2

      - name: Login to Container Registry
        if: ${{ needs.setup.outputs.docker-registry != '' }}
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ needs.setup.outputs.docker-registry }}
          username: ${{ needs.setup.outputs.deploy-target == 'scw' && 'nologin' || github.actor }}
          password: ${{ needs.setup.outputs.deploy-target == 'scw' && secrets.SCW_SECRET_KEY || secrets.GITHUB_TOKEN }}

      - name: Build dind-${{ needs.setup.outputs.docker-tag-suffix }} image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        env:
          SOURCE_DATE_EPOCH: 0 # No timestamps in layers
        with:
          platforms: linux/riscv64
          context: dind
          tags: |
            ${{ needs.setup.outputs.docker-registry != '' && format('{0}/riscv-runner:dind-{1}', needs.setup.outputs.docker-registry, needs.setup.outputs.docker-tag-suffix) || '' }}
          cache-from: |
            ${{ needs.setup.outputs.environment != '' && format('type=gha,scope=dind-{0}', needs.setup.outputs.environment) || '' }}
            ${{ needs.setup.outputs.environment == '' && format('type=gha,scope=dind-staging') || '' }}
          cache-to: |
            ${{ needs.setup.outputs.environment != '' && format('type=gha,scope=dind-{0},mode=max', needs.setup.outputs.environment) || '' }}
          push: ${{ needs.setup.outputs.docker-registry != '' }}
          pull: ${{ needs.setup.outputs.environment != '' }}
          outputs: ${{ needs.setup.outputs.docker-output }}

      - name: Upload dind image
        if: ${{ needs.setup.outputs.docker-output != '' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dind-image
          path: |
            ${{ needs.setup.outputs.docker-output-file }}

  deploy:
    if: ${{ needs.setup.outputs.deploy-target == 'scw' && needs.setup.outputs.environment != '' }}
    runs-on: ubuntu-latest
    needs: [setup, build-runner, build-dind]
    environment: ${{ needs.setup.outputs.environment }}
    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.K8S_KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Rollout Restart
        run: |
          kubectl rollout restart daemonset/rise-riscv-runner-device-plugin -n kube-system
          while ! kubectl rollout status daemonset/rise-riscv-runner-device-plugin -n kube-system --timeout=5m 2>/dev/null; do
            kubectl get pods -o wide -n kube-system -l app.kubernetes.io/name=riscv-runner-device-plugin -l app.kubernetes.io/component=device-plugin --sort-by=.spec.nodeName 2>/dev/null
          done
