name: Build and Release Github Actions Image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:

env:
  REGISTRY: rg.fr-par.scw.cloud/funcscwriseriscvrunnerappqdvknz9s
  IMAGE: riscv-runner
  RELEASE_ENVIRONMENT: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/staging' && 'staging') || '' }}

jobs:
  resolve:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
      external-contribution: ${{ steps.env.outputs.external-contribution }}
    steps:
      - id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=main" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi
          # Whether a PR comes from an non-"riseproject-dev" repository
          echo "external-contribution=${{ (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) && 'true' || 'false'  }}" >> $GITHUB_OUTPUT

  build-runner:
    strategy:
      matrix:
        include:
        - os: ubuntu
          os-version: 24.04
          runs-on: ubuntu-24.04-riscv
        # - os: ubuntu
        #   os-version: 26.04
        #   runs-on: ubuntu-latest # ubuntu-26.04-riscv-rva23 # Ubuntu 26.04 requires RVA23 hardware to run
    runs-on: ${{ matrix.runs-on }}
    needs: [resolve]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup slog values of GitHub env variables
        uses: rlespinasse/github-slug-action@9e7def61550737ba68c62d34a32dd31792e3f429 # v5.5.0

      - name: Setup QEMU
        if: matrix.runs-on == 'ubuntu-latest'
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2

      - name: Login to Container Registry
        if: needs.resolve.outputs.external-contribution == 'false'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build ${{ matrix.os }}-${{ matrix.os-version }} runner image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: runner
          file: runner/Dockerfile.${{ matrix.os }}
          platforms: linux/riscv64
          tags: |
            ${{ needs.resolve.outputs.environment == 'main' && format('{0}/{1}:{2}-{3}-latest', env.REGISTRY, env.IMAGE, matrix.os, matrix.os-version) || '' }}
            ${{ needs.resolve.outputs.environment != 'main' && format('{0}/{1}:{2}-{3}-{4}', env.REGISTRY, env.IMAGE, matrix.os, matrix.os-version, needs.resolve.outputs.environment || env.GITHUB_REF_NAME_SLUG) || '' }}
          build-args: |
            OS_VERSION=${{ matrix.os-version }}
          cache-from: |
            type=s3,endpoint_url=https://s3.fr-par.scw.cloud,region=fr-par,bucket=rise-riscv-runner-ci-cache,name=runner-${{ matrix.os }}-${{ matrix.os-version }}-${{ env.GITHUB_REF_NAME_SLUG }}
            ${{ github.event_name == 'pull_request' && format('type=s3,endpoint_url=https://s3.fr-par.scw.cloud,region=fr-par,bucket=rise-riscv-runner-ci-cache,name=runner-{0}-{1}-pr-{2}', matrix.os, matrix.os-version, github.event.pull_request.number) || '' }}
          cache-to: |
            type=s3,endpoint_url=https://s3.fr-par.scw.cloud,region=fr-par,bucket=rise-riscv-runner-ci-cache,name=runner-${{ matrix.os }}-${{ matrix.os-version }}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || env.GITHUB_REF_NAME_SLUG }},mode=max
          push: ${{ needs.resolve.outputs.external-contribution == 'false' }}

  build-dind:
    runs-on: ubuntu-24.04-riscv
    needs: [resolve]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup slog values of GitHub env variables
        uses: rlespinasse/github-slug-action@9e7def61550737ba68c62d34a32dd31792e3f429 # v5.5.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2

      - name: Login to Scaleway Container Registry
        if: needs.resolve.outputs.external-contribution == 'false'
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: rg.fr-par.scw.cloud/funcscwriseriscvrunnerappqdvknz9s
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build dind image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          platforms: linux/riscv64
          context: dind
          tags: |
            ${{ needs.resolve.outputs.environment == 'main' && format('{0}/{1}:dind-latest', env.REGISTRY, env.IMAGE) || '' }}
            ${{ needs.resolve.outputs.environment != 'main' && format('{0}/{1}:dind-{2}', env.REGISTRY, env.IMAGE, needs.resolve.outputs.environment || env.GITHUB_REF_NAME_SLUG) || '' }}
          cache-from: |
            type=s3,endpoint_url=https://s3.fr-par.scw.cloud,region=fr-par,bucket=rise-riscv-runner-ci-cache,name=dind-${{ env.GITHUB_REF_NAME_SLUG }}
            ${{ github.event_name == 'pull_request' && format('type=s3,endpoint_url=https://s3.fr-par.scw.cloud,region=fr-par,bucket=rise-riscv-runner-ci-cache,name=dind-pr-{0}', github.event.pull_request.number) || '' }}
          cache-to: |
            type=s3,endpoint_url=https://s3.fr-par.scw.cloud,region=fr-par,bucket=rise-riscv-runner-ci-cache,name=dind-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || env.GITHUB_REF_NAME_SLUG }},mode=max
          push: ${{ needs.resolve.outputs.external-contribution == 'false' }}

  deploy:
    if: ${{ needs.resolve.outputs.external-contribution == 'false' && needs.resolve.outputs.environment != '' }}
    runs-on: ubuntu-latest
    needs: [resolve, build-runner, build-dind]
    environment: ${{ needs.resolve.outputs.environment }}
    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.K8S_KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - run: |
          kubectl rollout restart daemonset/rise-riscv-runner-device-plugin -n kube-system
          kubectl rollout status daemonset/rise-riscv-runner-device-plugin -n kube-system --watch
